name: main - Release & Sync

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release-and-deploy:
    name: Release and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run semantic release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"

      - name: Publish release assets
        if: steps.release.outputs.released == 'true'
        uses: python-semantic-release/publish-action@v10.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}

  sync-branches:
    name: Sync main with dev
    needs: release-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Merge main into dev (fast-forward only)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"

          git fetch origin
          git checkout dev
          git pull origin dev
          git merge --ff-only origin/main || echo "Nothing to sync"
          git push origin dev
